services:
  postgres:
    image: postgres:16
    container_name: auth_role_jwt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass_123
      POSTGRES_DB: auth_practice
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_practice"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
